version: "3.7"
services:
  adaptation:
    image: "${AERIE_DOCKER_URL}/adaptation:${DOCKER_TAG}"
    ports: ["27182:27182"]
    depends_on: ["adaptation_mongo"]
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
  adaptation_mongo:
    command: ["mongod", "--port", "27020", "--smallfiles"]
    image: mongo:3.2
    ports: ["27020:27020"]
    volumes: ["adaptation_mongo_data:/data/db"]
  plan:
    image: "${AERIE_DOCKER_URL}/plan:${DOCKER_TAG}"
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: ["rabbitmq_data:/data/rabbitmq"]
  aerie_ui:
    image: "${AERIE_DOCKER_URL}/aerie-ui:${DOCKER_TAG}"
    ports: ["8080:80"]
  aerie_apollo:
    command: ["npm", "run", "start:docker"]
    image: "${AERIE_DOCKER_URL}/aerie-apollo:${DOCKER_TAG}"
    ports: ["27184:27184"]

volumes:
  adaptation_files:
  adaptation_mongo_data:
  plan_mongo_data:
  rabbitmq_data:
