version: "3.7"
services:
  merlin:
    image: "${AERIE_DOCKER_URL}/merlin:${DOCKER_TAG}"
    depends_on: ["merlin_mongo"]
    ports: ["27183:27183"]
    restart: always
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
  merlin_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["merlin_mongo_data:/data/db"]
  aerie_ui:
    command: ["npm", "run", "start:docker"]
    image: "${AERIE_DOCKER_URL}/aerie-ui:${DOCKER_TAG}"
    depends_on: ["postgres"]
    ports: ["80:80"]
  aerie_apollo:
    command: ["npm", "run", "start:docker"]
    image: "${AERIE_DOCKER_URL}/aerie-apollo:${DOCKER_TAG}"
    ports: ["27184:27184"]
  postgres:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: aerie
      POSTGRES_PASSWORD: aerie
      POSTGRES_USER: aerie
    restart: always
    volumes: ["postgres_data:/var/lib/postgresql/data"]

volumes:
  adaptation_files:
  merlin_mongo_data:
  postgres_data:
