version: "3.7"
services:
  adaptation:
    build:
      context: .
      dockerfile: scripts/dockerfiles/adaptation.Dockerfile
    depends_on: ["adaptation_mongo"]
    ports: ["27182:27182"]
    restart: always
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
  adaptation_mongo:
    command: ["mongod", "--port", "27020", "--smallfiles"]
    image: mongo:3.2
    ports: ["27020:27020"]
    volumes: ["adaptation_mongo_data:/data/db"]
  plan:
    build:
      context: .
      dockerfile: scripts/dockerfiles/plan.Dockerfile
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]
  postgres:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: aerie
      POSTGRES_PASSWORD: aerie
      POSTGRES_USER: aerie
    restart: always
    volumes: ["postgres_data:/var/lib/postgresql/data"]

volumes:
  adaptation_files:
  adaptation_mongo_data:
  plan_mongo_data:
  postgres_data:
