# This file configures the Hasura CLI, a local development (and deployment) tool.
# It is required to run the Hasura CLI (even if empty).

actions:
  handler_webhook_baseurl:
  kind:
endpoint:
metadata_directory:
migrations_directory:
seeds_directory:
version:
